#6.3 Excercises input
enter_key = input(" Please push any key then press enter")
print(enter_key)
enter_name = input("Please enter your name")
print(enter_name)
enter_age = input("Please enter your age")
print(enter_age)
user_name = input("please enter your username")
print(user_name)
var1= (user_name)
user_age = input("How old are you")
print(user_age)
var2= (user_age)
user_movie = input("What is your favourite movie")
print(user_movie)
var3= (user_movie)
user_book = input("What is your favourite book")
print(user_book)
va69= (user_book)
user_noun = input("Name a noun")
print(user_noun)
var73=(user_noun)
user_verb = input(" a verb please")
print(user_verb)
var4=(user_verb)
print(f"Cool username,{var1} is an awesome name!")
print(f"Imagine being {var2} years old, like grow up")
print(f"I never really got around to watching {user_movie}, looks pretty trash")
print(f"{user_book} isn't that good, how about getting a life.")
print(f"Oh that's a pretty cool {user_noun}, I don't really care tho")
print(f"Oh, so you are gonna go {user_verb}, lameee")
