#6.3 Excercises input
enter_key = input(" Please push any key then press enter")
print(enter_key)
enter_name = input("Please enter your name")
print(enter_name)
enter_age = input("Please enter your age")
print(enter_age)
user_name = input("please enter your username")
print(user_name)
var1= (user_name)
user_age = input("How old are you")
print(user_age)
var2= (user_age)
user_movie = input("What is your favourite movie")
print(user_movie)
var3= (user_movie)
user_book = input("What is your favourite book")
print(user_book)
va69= (user_book)
user_noun = input("Name a noun")
print(user_noun)
var73=(user_noun)
user_verb = input(" a verb please")
print(user_verb)
var4=(user_verb)
