print("Hello world")
print("My name is Juan")
print("Ms White")
print(" Kings high school")
print(2022-2006)
print("I spent 35 hours on GTA V")
print(2022+25)
print(16+100)
print(658/7)
print(2022-1969)
print("Wangan midnight")
print("Drama")
print("\n")
print(5+10.0)
print(10-5.0)
print(5/2)
print(5//2)
print(5%2)
print("\n")
print("She said, what you know 'bout love? \n I got what u need")
print("Life's a beach\nthen you drive")
print("String is characters that between quotation marks say something")
print("Integer is essentially number using operations makes numbers")
print("Float is essentially an integer that shows the decimals too")
print(543/3)
